version: '2'
services:
  db:
    image: mysql:5.7
    container_name: paperTest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=paperTest
      - MYSQL_DATABASE=paperTest
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=12345678
    networks:
      main:
        aliases:
          - paperTest
networks:
  main: